parserOptions:
  ecmaVersion: 2019
  sourceType: module
env:
  es6: true,
  browser: true
plugins:
  - svelte3
overrides:
  - files: '*.svelte'
    processor: svelte3/svelte3
    rules:
      import/first: off
      import/no-duplicates: off
      import/no-mutable-exports: off
      # bugs
      eol-last: off
      no-unused-expressions: off
